solution of 17

#include <iostream>
#include <vector>
using namespace std;

vector<int> increment(int N, vector<int>& arr) {
    for (int i = N - 1; i >= 0; i--) {
        if (arr[i] < 9) {
            arr[i]++;
            return arr;
        }
       
        arr[i] = 0;
    }
    arr.insert(arr.begin(), 1);
    return arr;
}

int main() {
    int N = 3;
    vector<int> arr = {9, 9, 9};

    vector<int> result = increment(N, arr);
    for (int digit: result) {
        cout << digit << " ";
    }
    cout << endl;

    return 0;
}

